// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt4qK6xisJY-SufUBRm5asGsMykmvbbu0',
    appId: '1:93233685937:web:8c1f3da2b705f1da2cc990',
    messagingSenderId: '93233685937',
    projectId: 'clone-8f771',
    authDomain: 'clone-8f771.firebaseapp.com',
    storageBucket: 'clone-8f771.appspot.com',
    measurementId: 'G-VH61SXV417',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmTL4_M8QKCNK0TrH82ZuoGjTybsTVnc',
    appId: '1:93233685937:android:9f6b19a2989199ac2cc990',
    messagingSenderId: '93233685937',
    projectId: 'clone-8f771',
    storageBucket: 'clone-8f771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC24Bf_rJPurfdxdzUIBkN2HQVm8Stk0so',
    appId: '1:93233685937:ios:1895f0d95d92e92d2cc990',
    messagingSenderId: '93233685937',
    projectId: 'clone-8f771',
    storageBucket: 'clone-8f771.appspot.com',
    iosBundleId: 'com.example.rentcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC24Bf_rJPurfdxdzUIBkN2HQVm8Stk0so',
    appId: '1:93233685937:ios:1895f0d95d92e92d2cc990',
    messagingSenderId: '93233685937',
    projectId: 'clone-8f771',
    storageBucket: 'clone-8f771.appspot.com',
    iosBundleId: 'com.example.rentcar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZX1fDwzgm12Ym_XZhyP7nj3yhdSWUebA',
    appId: '1:93233685937:web:cadb03b9a0f1083b2cc990',
    messagingSenderId: '93233685937',
    projectId: 'clone-8f771',
    authDomain: 'clone-8f771.firebaseapp.com',
    storageBucket: 'clone-8f771.appspot.com',
    measurementId: 'G-PH4B9LBX6K',
  );
}
